/**
 * Placeholder services shown when no AgencyService rows exist in the database yet.
 * Shared between the homepage services section and the /services/[slug] detail
 * page so links always resolve to something, even before an admin has added
 * real services.
 */
export const fallbackServices = [
  {
    id: "web-design",
    slug: "web-design",
    iconName: "Globe",
    title: "Web Design & Development",
    subtitle: "Conversion-focused websites",
    description:
      "Custom-built, mobile-first websites designed to convert visitors into customers. Fast, SEO-optimized, and built with modern frameworks.",
    detailTitle: null as string | null,
    detailIntro: null as string | null,
    content: null as string | null,
    features: JSON.stringify([
      { icon: "Monitor", text: "Responsive Design" },
      { icon: "Palette", text: "UI/UX Excellence" },
      { icon: "Code2", text: "Next.js & React" },
      { icon: "Zap", text: "Performance Optimized" },
    ]),
    process: JSON.stringify([
      { step: 1, title: "Discovery", desc: "Understand your brand, audience & goals" },
      { step: 2, title: "Design", desc: "Create wireframes & visual designs" },
      { step: 3, title: "Build", desc: "Develop with modern frameworks" },
      { step: 4, title: "Launch", desc: "Test, optimize & deploy" },
    ]),
    deliverables: JSON.stringify(["Figma Design Files", "Source Code", "Documentation", "30 Days Support"]),
    gradient: "from-brand-orange-deep to-brand-orange",
    bgGradient: "from-brand-orange/10 to-brand-orange/10",
    shadowColor: "shadow-brand-orange/20",
    statValue: "98%",
    statLabel: "PageSpeed Score",
    metaTitle: null as string | null,
    metaDescription: null as string | null,
    ogImage: null as string | null,
    twitterCard: null as string | null,
    ogTitle: null as string | null,
    ogDescription: null as string | null,
    twitterTitle: null as string | null,
    twitterDescription: null as string | null,
    twitterImage: null as string | null,
    isIndexable: true,
    faqs: [] as { id: string; question: string; answer: string; order: number }[],
  },
  {
    id: "smm",
    slug: "smm",
    iconName: "Share2",
    title: "Social Media Marketing",
    subtitle: "Build your community",
    description:
      "Strategic social media management across all major platforms. Content creation, community engagement, and paid social campaigns that drive real results.",
    detailTitle: null as string | null,
    detailIntro: null as string | null,
    content: null as string | null,
    features: JSON.stringify([
      { icon: "Users", text: "Community Growth" },
      { icon: "MessageSquare", text: "Content Strategy" },
      { icon: "Megaphone", text: "Paid Social Ads" },
      { icon: "TrendingUp", text: "Analytics & Insights" },
    ]),
    process: JSON.stringify([
      { step: 1, title: "Strategy", desc: "Define audience & platform mix" },
      { step: 2, title: "Create", desc: "Design content calendar & assets" },
      { step: 3, title: "Engage", desc: "Post, respond & grow community" },
      { step: 4, title: "Optimize", desc: "Analyze & refine strategy" },
    ]),
    deliverables: JSON.stringify(["Content Calendar", "Brand Assets", "Monthly Analytics", "Growth Strategy"]),
    gradient: "from-charcoal to-off-black",
    bgGradient: "from-charcoal/10 to-off-black/10",
    shadowColor: "shadow-charcoal/20",
    statValue: "2.5M+",
    statLabel: "Monthly Reach",
    metaTitle: null as string | null,
    metaDescription: null as string | null,
    ogImage: null as string | null,
    twitterCard: null as string | null,
    ogTitle: null as string | null,
    ogDescription: null as string | null,
    twitterTitle: null as string | null,
    twitterDescription: null as string | null,
    twitterImage: null as string | null,
    isIndexable: true,
    faqs: [] as { id: string; question: string; answer: string; order: number }[],
  },
];
